run_name: "test_on_larger_data"
data:
  num_patients: 512
  test_fraction: 0.20
  batch_size: 8
  seed: 81
  device: cpu
model:
  n_subtypes: 3
  n_cell_types: 8
  n_genes: 500
  z_dim: 10
  u_dim: 10
  subtype_concentration: 2.0
  subtype_rate: 0.1
  nb_dispersion_prior: 2.0
  nb_dispersion_rate: 1.0
vi:
  early_stopping_patience: 40
  learning_rate: 0.003
  num_epochs: 200
  log_interval: 100
  guide: auto_normal
